### ISSUE TITLE
Create read binary file and write binary file

### ISSUE THREAD

**Issue by victorcmoura** [projeto-de-algoritmos-2019-2/project-3-huffman-code-cli#1]
Currently, there is no option to decipher text from a binary file. The huffman content should be given to the decipher as an ascii string. E.g: '001101010'.

There should be a way to write this plain binary to a real binary file in order to achieve real compression.

It should also be good to decipher those compressed files into plain text again.

**Comment by durvalcarvalho** [comment]
done
